### PR TITLE
DevOpsDayJKT18 blogpost

### PR DESCRIPTION
**Pull request by empeje**
WIP: devopsdayjkt18 blogpost

## Testing recommendations

     
**Standard way**:

Prerequisites:
* [Docker](https://docs.docker.com/install/linux/docker-ce/ubuntu/#install-docker-ce)
* [`docker-compose`](https://docs.docker.com/compose/install/#install-compose)

Command:

Run the following command in you machine

```bash
docker-compose up
```

Then open `localhost:4000` on your browser.

## Checklist

- [x] Code & Markdown is written and works correctly;
- [x] Documentation reflects the changes;

### CODE REVIEW

**Review by dogi — COMMENTED** [review]
@mappuji is this still a work in progress?

**Comment by empeje** [comment]
Yes @dogi , let me finish it and get back to you.

**Comment by empeje** [comment]
Finished @dogi

**Comment by empeje** [comment]
Any concern @dogi and @xyb994? If not I'll merge this at least on Monday.

**Review by xyb994 — APPROVED** [review]

**Pull request merged**
